---
- name: Update apt
  apt: update_cache=yes

- name: Add apt repository key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: Add repository to sources
  lineinfile: dest="/etc/apt/sources.list.d/jenkins.list" line="deb http://pkg.jenkins-ci.org/debian binary/" state=present create=yes

- name: Install jenkins
  apt: name=jenkins state=latest force=yes update_cache=yes

- name: Create nginx configuration
  template:
    src: vhost-configuration.j2
    dest: /etc/nginx/sites-available/jenkins-configuration.conf

- name: Enable nginx vhosts
  file:
    src: /etc/nginx/sites-available/jenkins-configuration.conf
    dest: /etc/nginx/sites-enabled/jenkins-configuration.conf
    state: link
    mode: 600
    owner: www-data
    force: yes
  notify:
   - restart nginx

- name: Waiting for jenkins running
  wait_for: path=/etc/init.d/jenkins state=started delay=120

- name: Download jenkins cli
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/usr/share/jenkins/jenkins-cli.jar mode=0777

- name: Update plugins list
  shell: "curl  -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"

- name: List plugins
  shell: java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 list-plugins | cut -f 1 -d ' '
  when: jenkins_plugins is defined
  register: plugins_installed

- name: Install jenkins plugins required for above libs
  shell: java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 install-plugin {{ item }}
  when: plugins_installed.changed and plugins_installed.stdout.find('{{ item }}') == -1
  with_items: jenkins_plugins
  ignore_errors: yes
  notify:
   - restart jenkins
